seed: 42
mode: 'val'
data :
  name            : Scan3R
  root_dir        : '' # to be read in code from env varia  
  rescan: True
  resplit: True
  log_dir: ""
  img:
    img_step: 1
    w: 960
    h: 540
  img_encoding:
    # image patch config
    resize_w: 1024 # resize image for backbone GCVit
    resize_h: 576
    img_rotate: True # rotate w,h for backbone GCVit
    feature_dir: "Features2D/OpenSeg_16_9_scan"
  obj_img:
    topk: 5
    name: "Features3D/obj_openmask3d_top5"
  feat_dim: 768
  cross_scene:
    use_cross_scene: True
    num_scenes: 49 # number of scenes 
    num_negative_samples: -1 # number of negative samples 


# for sgaligner
sgaligner:
  use_pretrained : True
  pretrained: "./checkpoint/sgaligner/gat-point-rel-attr-epoch-50.pth.tar"

  label_file_name : labels.instances.annotated.v2.ply
  pred_subfix     : inseg.ply

  seed: 42
  model_name    : 'sgaligner'
  modules       : ['point', 'gat', 'rel', 'attr']
  use_predicted : False
  registration  : False
  scan_type     : 'scan'

  preprocess :
    pc_resolutions      : [64, 128, 256, 512]
    subscenes_per_scene : 1
    filter_segment_size : 512
    min_obj_points      : 50
    anchor_type_name    : '' 

  model :
    rel_dim             : 41
    attr_dim            : 164
    alignment_thresh    : 0.4

  train :
    pc_res: 512

  val :
    pc_res: 512
    overlap_low         : 0.0
    overlap_high        : 0.0
    data_mode: orig

# for validation
val:
  batch_size: 8
  num_workers: 2
  pretrained: "./"
  room_retrieval:
    epsilon_th: 0.8
    method_name: "OpenMask3D_scan3r_X50"