name: gpu_gnn_project
channels:
  - pytorch
  - pyg
  - nvidia
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.0.140
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.140
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - gds-tools=1.5.1.14
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.1.14
  - libcufile-dev=1.5.1.14
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - nsight-compute=2022.4.1.6
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1s
  - pillow=9.4.0
  - pip=22.3.1
  - psutil=5.9.0
  - pycparser=2.21
  - pyg=2.2.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.16
  - pytorch=1.13.1
  - pytorch-cluster=1.6.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.15
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.14.1
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - absl-py==1.4.0
      - albumentations==1.3.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - backports-cached-property==1.0.2
      - cachetools==5.3.0
      - click==8.1.3
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.14.1
      - filelock==3.12.0
      - flatbuffers==23.1.21
      - fonttools==4.38.0
      - frozendict==2.3.8
      - fsspec==2023.1.0
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h5py==3.8.0
      - huggingface-hub==0.14.1
      - imageio==2.25.1
      - importlib-metadata==6.0.0
      - keras==2.11.0
      - kiwisolver==1.4.4
      - libclang==15.0.6.1
      - liegroups==0.11
      - markdown==3.4.1
      - markdown-it-py==2.2.0
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - mpmath==1.2.1
      - networkx==2.6.3
      - oauthlib==3.2.2
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.7.0.72
      - opt-einsum==3.3.0
      - packaging==23.0
      - pathtools==0.1.2
      - plotly==5.13.0
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.15.1
      - python-dateutil==2.8.2
      - pywavelets==1.3.0
      - pyyaml==6.0
      - qudida==0.0.4
      - rdkit==2022.9.4
      - requests-oauthlib==1.3.1
      - rich==13.4.1
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-image==0.19.3
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - shtab==1.6.1
      - smmap==5.0.0
      - sympy==1.10.1
      - tenacity==8.2.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - tifffile==2021.11.2
      - timm==0.9.2
      - tyro==0.5.3
      - wandb==0.15.4
      - werkzeug==2.2.3
      - wrapt==1.14.1
      - xyz2graph==2.0.0
      - zipp==3.14.0
